// <auto-generated />
using CrazyToys.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrazyToys.Web.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgeGroupToy", b =>
                {
                    b.Property<string>("AgeGroupsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToysId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AgeGroupsId", "ToysId");

                    b.HasIndex("ToysId");

                    b.ToTable("AgeGroupToy");
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.AgeGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IdAgeGroup");

                    b.Property<string>("Interval")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgeGroups");
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.Brand", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IdBrand");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.Category", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.Colour", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IdColour");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colours");
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IdImage");

                    b.Property<string>("ToyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UrlHigh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlLow")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ToyId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.SubCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IdSubCategory");

                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.Toy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IdToy");

                    b.Property<string>("BrandId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColourId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColourId");

                    b.ToTable("Toys");
                });

            modelBuilder.Entity("SubCategoryToy", b =>
                {
                    b.Property<string>("SubCategoriesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToysId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubCategoriesId", "ToysId");

                    b.HasIndex("ToysId");

                    b.ToTable("SubCategoryToy");
                });

            modelBuilder.Entity("AgeGroupToy", b =>
                {
                    b.HasOne("CrazyToys.Web.Models.Entities.AgeGroup", null)
                        .WithMany()
                        .HasForeignKey("AgeGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrazyToys.Web.Models.Entities.Toy", null)
                        .WithMany()
                        .HasForeignKey("ToysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.Image", b =>
                {
                    b.HasOne("CrazyToys.Web.Models.Entities.Toy", null)
                        .WithMany("Images")
                        .HasForeignKey("ToyId");
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.SubCategory", b =>
                {
                    b.HasOne("CrazyToys.Web.Models.Entities.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryID");
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.Toy", b =>
                {
                    b.HasOne("CrazyToys.Web.Models.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("CrazyToys.Web.Models.Entities.Colour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourId");

                    b.Navigation("Brand");

                    b.Navigation("Colour");
                });

            modelBuilder.Entity("SubCategoryToy", b =>
                {
                    b.HasOne("CrazyToys.Web.Models.Entities.SubCategory", null)
                        .WithMany()
                        .HasForeignKey("SubCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrazyToys.Web.Models.Entities.Toy", null)
                        .WithMany()
                        .HasForeignKey("ToysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("CrazyToys.Web.Models.Entities.Toy", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
